services:
  - type: web
    name: Photo_Fail_Russian_Roulette
    env: python
    buildCommand: |
      pip install --no-cache-dir -r requirements.txt
      chmod +x download_model.sh
      ./download_model.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_DEBUG
        value: False